package com.liangge.databasedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ORDER".
 */
public class Order {

    private int productId;
    private int buyCnt;

    public Order() {
    }

    public Order(int productId) {
        this.productId = productId;
    }

    public Order(int productId, int buyCnt) {
        this.productId = productId;
        this.buyCnt = buyCnt;
    }

    public int getProductId() {
        return productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    public int getBuyCnt() {
        return buyCnt;
    }

    public void setBuyCnt(int buyCnt) {
        this.buyCnt = buyCnt;
    }

}
